// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/proto/v1/candles.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CandlesService_SubscribeCandles_FullMethodName = "/v1.CandlesService/SubscribeCandles"
)

// CandlesServiceClient is the client API for CandlesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CandlesService provides a real-time stream of OHLC candles.
type CandlesServiceClient interface {
	// SubscribeCandles opens a server-side stream to send candles to the client.
	SubscribeCandles(ctx context.Context, in *SubscribeCandlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candle], error)
}

type candlesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandlesServiceClient(cc grpc.ClientConnInterface) CandlesServiceClient {
	return &candlesServiceClient{cc}
}

func (c *candlesServiceClient) SubscribeCandles(ctx context.Context, in *SubscribeCandlesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CandlesService_ServiceDesc.Streams[0], CandlesService_SubscribeCandles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeCandlesRequest, Candle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CandlesService_SubscribeCandlesClient = grpc.ServerStreamingClient[Candle]

// CandlesServiceServer is the server API for CandlesService service.
// All implementations must embed UnimplementedCandlesServiceServer
// for forward compatibility.
//
// CandlesService provides a real-time stream of OHLC candles.
type CandlesServiceServer interface {
	// SubscribeCandles opens a server-side stream to send candles to the client.
	SubscribeCandles(*SubscribeCandlesRequest, grpc.ServerStreamingServer[Candle]) error
	mustEmbedUnimplementedCandlesServiceServer()
}

// UnimplementedCandlesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCandlesServiceServer struct{}

func (UnimplementedCandlesServiceServer) SubscribeCandles(*SubscribeCandlesRequest, grpc.ServerStreamingServer[Candle]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeCandles not implemented")
}
func (UnimplementedCandlesServiceServer) mustEmbedUnimplementedCandlesServiceServer() {}
func (UnimplementedCandlesServiceServer) testEmbeddedByValue()                        {}

// UnsafeCandlesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandlesServiceServer will
// result in compilation errors.
type UnsafeCandlesServiceServer interface {
	mustEmbedUnimplementedCandlesServiceServer()
}

func RegisterCandlesServiceServer(s grpc.ServiceRegistrar, srv CandlesServiceServer) {
	// If the following call pancis, it indicates UnimplementedCandlesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CandlesService_ServiceDesc, srv)
}

func _CandlesService_SubscribeCandles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCandlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CandlesServiceServer).SubscribeCandles(m, &grpc.GenericServerStream[SubscribeCandlesRequest, Candle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CandlesService_SubscribeCandlesServer = grpc.ServerStreamingServer[Candle]

// CandlesService_ServiceDesc is the grpc.ServiceDesc for CandlesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandlesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CandlesService",
	HandlerType: (*CandlesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCandles",
			Handler:       _CandlesService_SubscribeCandles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/v1/candles.proto",
}
